# general settings
name: DefocusDeblur_Single_8bit_IPT
model_type: ImageCleanModel
scale: 1
num_gpu: 4  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: ../SCASDNet/data/RainDrop_blur/train/target
    dataroot_lq: ../SCASDNet/data/RainDrop_blur/train/input
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16

    ### -------------Progressive training--------------------------
    #mini_batch_sizes: [4,2,1,1]             # Batch size per gpu   
    #iters: [92000,112000,54000,42000]
    #gt_size: 256   # Max patch size for progressive training
    #gt_sizes: [128,160,192,256]  # Patch sizes for progressive training.
    ### ------------------------------------------------------------

    ### ------- Training on single fixed-patch size 128x128---------
    mini_batch_sizes: [16]
    iters: [300000]
    gt_size: 48
    gt_sizes: [48]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: ../SCASDNet/data/RainDrop_blur/val/target
    dataroot_lq: ../SCASDNet/data/RainDrop_blur/val/input
    gt_size: 48
    io_backend:
      type: disk

# network structures
network_g:
  type: ipt
  scale_idx: 3
  n_feats: 64
  rgb_range: 255
  n_colors: 3
  scale: [2,3,4,1,1,1]
  patch_size: 48
  patch_dim: 3
  num_heads: 12
  num_layers: 12
  num_queries: 6
  dropout_rate: 0
  no_mlp: False
  pos_every: False
  no_pos: False
  no_norm: False


# path
path:
  pretrain_network_g: ./pretrained/IPT_pretrain.pt
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 300000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [92000, 208000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 4e3
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 4e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
# important
find_unused_parameters: true
